# Generated by Django 3.0.3 on 2020-02-17 19:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralChemistry2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectureName', models.CharField(max_length=200)),
                ('professorName', models.CharField(max_length=50)),
                ('seme', models.CharField(choices=[('19년도 2학기', '19년도 2학기'), ('19년도 1학기', '19년도 1학기'), ('18년도 2학기', '18년도 2학기'), ('18년도 2학기', '18년도 1학기')], max_length=10)),
                ('score', models.IntegerField(default=[0], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(max_length=300)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
