# Generated by Django 3.0.3 on 2020-02-19 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_lawandeconomics_physicsexperiment_webprogramming'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalchemistry2',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
