# Generated by Django 3.0.3 on 2020-02-19 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_generalchemistry2_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawandeconomics',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='physicsexperiment',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='webprogramming',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
