# Generated by Django 3.0.3 on 2020-02-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalchemistry2',
            name='professorName',
            field=models.CharField(default='최슬옹', max_length=50),
        ),
    ]
