# Generated by Django 3.0.3 on 2020-02-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200221_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalchemistry2',
            name='professorName',
            field=models.CharField(max_length=50),
        ),
    ]
