# Generated by Django 3.0.3 on 2020-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200222_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalchemistry2',
            name='lectureName',
            field=models.CharField(default='일반화학2', max_length=200),
        ),
        migrations.AlterField(
            model_name='generalchemistry2',
            name='professorName',
            field=models.CharField(default='세아', max_length=50),
        ),
    ]
