# Generated by Django 2.2.3 on 2020-02-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200222_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalchemistry2',
            name='professorName',
            field=models.CharField(default='민선준', max_length=50),
        ),
        migrations.AlterField(
            model_name='physicsexperiment',
            name='lectureName',
            field=models.CharField(default='일반물리학실험', max_length=200),
        ),
        migrations.AlterField(
            model_name='physicsexperiment',
            name='professorName',
            field=models.CharField(default='오혜근', max_length=50),
        ),
        migrations.AlterField(
            model_name='webprogramming',
            name='professorName',
            field=models.CharField(default='최기환', max_length=50),
        ),
    ]
