# Generated by Django 3.0.3 on 2020-02-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200223_0044'),
        ('app', '0012_auto_20200222_2142'),
    ]

    operations = [
    ]
