# Generated by Django 2.2.3 on 2020-02-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200222_2142'),
        ('app', '0011_auto_20200223_0044'),
    ]

    operations = [
    ]
